In [2]:
import numpy as np

def Gradient_descent(x,y):
    m_curr = b_curr = 0
    iterations = 2000
    n = len(x)
    learning_rate = 0.01
    for i in range(iterations):
        y_predicted = m_curr * x + b_curr
        cost = (1/n) * sum(val**2 for val in (y - y_predicted))
        md = -(2/n) * sum(x* (y - y_predicted))
        bd = -(2/n) * sum(y - y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd
        print('m{} , b{} , cost{}, iterations{}, learning_rate{}2e'.format(m_curr, b_curr, round(cost, 4), i, learning_rate))
    
x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13]) 
Gradient_descent(x, y)

m0.62 , b0.18 , cost89.0, iterations0, learning_rate0.012e
m1.0928 , b0.3192 , cost52.2504, iterations1, learning_rate0.012e
m1.453232 , b0.42724799999999996 , cost30.8319, iterations2, learning_rate0.012e
m1.7278860800000002 , b0.5115091199999999 , cost18.3478, iterations3, learning_rate0.012e
m1.9370605952000002 , b0.5776057727999999 , cost11.07, iterations4, learning_rate0.012e
m2.096250917888 , b0.6298300216319999 , cost6.8264, iterations5, learning_rate0.012e
m2.2172859146547204 , b0.6714583661260799 , cost4.3508, iterations6, learning_rate0.012e
m2.309195511463117 , b0.7049920439242751 , cost2.9057, iterations7, learning_rate0.012e
m2.3788729763057748 , b0.7323404723580026 , cost2.061, iterations8, learning_rate0.012e
m2.431580493177024 , b0.7549612843324961 , cost1.5663, iterations9, learning_rate0.012e
m2.471335107618129 , b0.7739672290552247 , cost1.2756, iterations10, learning_rate0.012e
m2.501203350198827 , b0.7902077780170325 , cost1.1037, iterations11, learning_rate0.012e


m2.018149487989657 , b2.9344745895559856 , cost0.0008, iterations1046, learning_rate0.012e
m2.0180881252585734 , b2.9346961284854864 , cost0.0008, iterations1047, learning_rate0.012e
m2.018026969992558 , b2.9349169184002624 , cost0.0008, iterations1048, learning_rate0.012e
m2.01796602149018 , b2.9351369618327037 , cost0.0008, iterations1049, learning_rate0.012e
m2.017905279052378 , b2.9353562613066386 , cost0.0008, iterations1050, learning_rate0.012e
m2.0178447419824566 , b2.935574819337363 , cost0.0008, iterations1051, learning_rate0.012e
m2.017784409586074 , b2.9357926384316686 , cost0.0008, iterations1052, learning_rate0.012e
m2.0177242811712377 , b2.9360097210878706 , cost0.0008, iterations1053, learning_rate0.012e
m2.017664356048293 , b2.936226069795839 , cost0.0007, iterations1054, learning_rate0.012e
m2.0176046335299183 , b2.9364416870370245 , cost0.0007, iterations1055, learning_rate0.012e
m2.017545112931115 , b2.936656575284489 , cost0.0007, iterations1056, learning_rate0.012e

m2.004259444824558 , b2.984622052668823 , cost0.0, iterations1474, learning_rate0.012e
m2.0042450438030257 , b2.984674044925973 , cost0.0, iterations1475, learning_rate0.012e
m2.0042306914708017 , b2.984725861399272 , cost0.0, iterations1476, learning_rate0.012e
m2.004216387663269 , b2.9847775026830385 , cost0.0, iterations1477, learning_rate0.012e
m2.0042021322163674 , b2.9848289693695818 , cost0.0, iterations1478, learning_rate0.012e
m2.0041879249665917 , b2.984880262049208 , cost0.0, iterations1479, learning_rate0.012e
m2.004173765750989 , b2.9849313813102283 , cost0.0, iterations1480, learning_rate0.012e
m2.004159654407158 , b2.9849823277389644 , cost0.0, iterations1481, learning_rate0.012e
m2.0041455907732453 , b2.985033101919756 , cost0.0, iterations1482, learning_rate0.012e
m2.004131574687946 , b2.985083704434966 , cost0.0, iterations1483, learning_rate0.012e
m2.0041176059905 , b2.98513413586499 , cost0.0, iterations1484, learning_rate0.012e
m2.0041036845206905 , b2.985184396788

In [3]:
import seaborn as sns


In [4]:
import pandas as pd
df = pd.read_csv('F:\\Book1.csv')
display(df)

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [7]:
import math
def gradient_des_math(x,y):
    iterations = 1000
    learning_rate = 0.0000001
    m_curr = b_curr = 0
    n = len(x)
    b = 0
    for i in range(iterations):
        y_predicted = m_curr*x + b_curr
        cost = (1/n) * sum(val**2 for val in (y - y_predicted))
        md = -(2/n)* sum(x*(y - y_predicted))
        bd = (2/n) * sum(y - y_predicted)
        m_curr = m_curr - learning_rate *md
        b_curr = b_curr - learning_rate * bd
        print('m{}, b{}, iterations{}, cost{}'.format(m_curr, b_curr, i, cost))
from sklearn.preprocessing import MinMaxScaler
min = MinMaxScaler()
trans= min.fit_transform([df['cs'], df['math']])
gradient_des_math(trans[0], trans[1])


m0.0, b-4e-08, iterations0, cost0.2
m6.399999999999999e-15, b-8.0000008e-08, iterations1, cost0.2000000160000016
m1.9200000256e-14, b-1.2000002400000058e-07, iterations2, cost0.2000000320000096
m3.840000102400005e-14, b-1.600000480000023e-07, iterations3, cost0.20000004800002397
m6.400000256000026e-14, b-2.0000008000000576e-07, iterations4, cost0.20000006400004483
m9.600000512000078e-14, b-2.4000012000001153e-07, iterations5, cost0.200000080000072
m1.344000089600018e-13, b-2.8000016800002016e-07, iterations6, cost0.20000009600010557
m1.792000143360036e-13, b-3.2000022400003227e-07, iterations7, cost0.2000001120001456
m2.304000215040065e-13, b-3.600002880000484e-07, iterations8, cost0.20000012800019207
m2.880000307200108e-13, b-4.0000036000006916e-07, iterations9, cost0.2000001440002449
m3.520000422400169e-13, b-4.4000044000009506e-07, iterations10, cost0.20000016000030404
m4.224000563200254e-13, b-4.800005280001267e-07, iterations11, cost0.20000017600036968
m4.992000732160367e-13, b-5.

In [6]:
from sklearn.linear_model import LinearRegression
trans.reshape(-1,1)
trans.reshape(1,-1)
lin_reg = LinearRegression()
lin_mod = lin_reg.fit([trans[1]], [trans[0]])
print(lin_mod.coef_)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
